name: Update Website

on:
  push:
    branches:
      - main

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy website folder into website branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          git checkout 'website' --
          git rm -r .
          git checkout 'main' -- 'website'
          mv website/* .
          rm -r website
          git add -A
          git diff-index --quiet HEAD ||  git commit -am ${github.event.head_commit.message}
          git push origin 'website'
