name: Update Website

on:
  push:
    branches:
      - main

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy website folder into website branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          files=$(find 'website')
          git checkout refs/heads/website
          git checkout 'main' -- $files
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "update website"
          git push origin refs/heads/website
